export const subscriptionsMockData = [
	{
		id: 1,
		name: "Netflix",
		amount: 799,
		dueDate: "2024-01-15",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 399.5,
		status: "paid",
		category: "Entertainment",
	},
	{
		id: 2,
		name: "Spotify",
		amount: 119,
		dueDate: "2024-01-20",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 59.5,
		status: "paid",
		category: "Entertainment",
	},
	{
		id: 3,
		name: "YouTube Premium",
		amount: 129,
		dueDate: "2024-01-25",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 64.5,
		status: "pending",
		category: "Entertainment",
	},
	{
		id: 4,
		name: "Internet",
		amount: 1500,
		dueDate: "2024-01-30",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 750,
		status: "due",
		category: "Utilities",
	},
	{
		id: 5,
		name: "Electricity",
		amount: 2500,
		dueDate: "2024-01-28",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 1250,
		status: "pending",
		category: "Utilities",
	},
	{
		id: 6,
		name: "Amazon Prime",
		amount: 129,
		dueDate: "2024-02-05",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 64.5,
		status: "paid",
		category: "Entertainment",
	},
	{
		id: 7,
		name: "Disney+",
		amount: 199,
		dueDate: "2024-02-10",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 99.5,
		status: "pending",
		category: "Entertainment",
	},
	{
		id: 8,
		name: "Hulu",
		amount: 599,
		dueDate: "2024-02-15",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 299.5,
		status: "due",
		category: "Entertainment",
	},
	{
		id: 9,
		name: "HBO Max",
		amount: 149,
		dueDate: "2024-02-20",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 74.5,
		status: "paid",
		category: "Entertainment",
	},
	{
		id: 10,
		name: "Apple Music",
		amount: 99,
		dueDate: "2024-02-25",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 49.5,
		status: "paid",
		category: "Entertainment",
	},
	{
		id: 11,
		name: "Google Drive",
		amount: 199,
		dueDate: "2024-03-01",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 99.5,
		status: "pending",
		category: "Utilities",
	},
	{
		id: 12,
		name: "Dropbox",
		amount: 129,
		dueDate: "2024-03-05",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 64.5,
		status: "due",
		category: "Utilities",
	},
	{
		id: 13,
		name: "Slack",
		amount: 299,
		dueDate: "2024-03-10",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 149.5,
		status: "paid",
		category: "Utilities",
	},
	{
		id: 14,
		name: "Zoom",
		amount: 199,
		dueDate: "2024-03-15",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 99.5,
		status: "pending",
		category: "Utilities",
	},
];

export type Subscription = (typeof subscriptionsMockData)[number];
