export const expensesMockData = [
	{
		id: 1,
		description: "Grocery Shopping",
		amount: 2400,
		date: "2024-01-10",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 1200,
		status: "paid",
		category: "Groceries",
	},
	{
		id: 2,
		description: "Dinner at Restaurant",
		amount: 1800,
		date: "2024-01-08",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 900,
		status: "pending",
		category: "Food",
	},
	{
		id: 3,
		description: "Coffee Beans",
		amount: 800,
		date: "2024-01-05",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 400,
		status: "paid",
		category: "Groceries",
	},
	{
		id: 4,
		description: "Uber Ride",
		amount: 450,
		date: "2024-01-03",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 225,
		status: "pending",
		category: "Transportation",
	},
	{
		id: 5,
		description: "Movie Tickets",
		amount: 1200,
		date: "2024-01-01",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 600,
		status: "paid",
		category: "Entertainment",
	},
	{
		id: 6,
		description: "Gym Membership",
		amount: 1500,
		date: "2024-01-05",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 750,
		status: "pending",
		category: "Health and Wellness",
	},
	{
		id: 7,
		description: "Clothing Shopping",
		amount: 2800,
		date: "2024-01-12",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 1400,
		status: "paid",
		category: "Clothing",
	},
	{
		id: 8,
		description: "Lunch at Cafe",
		amount: 900,
		date: "2024-01-15",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 450,
		status: "pending",
		category: "Food",
	},
	{
		id: 9,
		description: "Petrol",
		amount: 1200,
		date: "2024-01-18",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 600,
		status: "paid",
		category: "Transportation",
	},
	{
		id: 10,
		description: "Dinner at Home",
		amount: 1800,
		date: "2024-01-20",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 900,
		status: "pending",
		category: "Food",
	},
	{
		id: 11,
		description: "Flowers",
		amount: 800,
		date: "2024-01-22",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 400,
		status: "paid",
		category: "Gifts",
	},
	{
		id: 12,
		description: "Parking Fee",
		amount: 200,
		date: "2024-01-25",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 100,
		status: "pending",
		category: "Transportation",
	},
	{
		id: 13,
		description: "Hotel Stay",
		amount: 4000,
		date: "2024-01-28",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 2000,
		status: "paid",
		category: "Travel",
	},
	{
		id: 14,
		description: "Dinner at Restaurant",
		amount: 2500,
		date: "2024-01-30",
		paidBy: "Alex",
		owedBy: "Rohan",
		owedAmount: 1250,
		status: "pending",
		category: "Food",
	},
	{
		id: 15,
		description: "Movie Tickets",
		amount: 1800,
		date: "2024-02-01",
		paidBy: "Rohan",
		owedBy: "Alex",
		owedAmount: 900,
		status: "paid",
		category: "Entertainment",
	},
];

export type Expense = (typeof expensesMockData)[number];
